application:
  host: 0.0.0.0
  base_url: "https://zero2prod-production-dylf.up.railway.app"
database:
  require_ssl: true
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "something@gmail.com"
